Added some debug on strange errors in cleanup. Changed host:das4 to take together all instances of host:das4 and make one big reservation, dividing the nodes among all host:das4 instances. Fixed some small debugging in run_campaign.

diff --git a/ControlScripts/modules/host/das4 b/ControlScripts/modules/host/das4
--- a/ControlScripts/modules/host/das4
+++ b/ControlScripts/modules/host/das4
@@ -189,17 +189,25 @@ function hostReadSettings() {
     # echo "YOUR_SETTING=\"$YOUR_SETTING\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_HEADNODE=\"$HOST_DAS4_HEADNODE\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_NNODES=\"$HOST_DAS4_NNODES\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+    echo "HOST_DAS4_NNODES_ALL=\"$HOST_DAS4_NNODES\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_RESERVETIME=\"$HOST_DAS4_RESERVETIME\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_NODENAME=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_NODENUMBER=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+    echo "HOST_DAS4_MASTER=\"1\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_SLAVE=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_LOCALTEMPDIRECTORY=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     echo "HOST_DAS4_RESERVATIONID=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+    echo "HOST_DAS4_MYNODES=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+    echo "HOST_DAS4_MYNODENUMBER=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     HOST_DAS4_NODENAME=""
     HOST_DAS4_NODENUMBER=""
+    HOST_DAS4_MASTER="1"
     HOST_DAS4_SLAVE=""
     HOST_DAS4_LOCALTEMPDIRECTORY=""
     HOST_DAS4_RESERVATIONID=""
+    HOST_DAS4_NNODES_ALL=$HOST_DAS4_NNODES
+    HOST_DAS4_MYNODES=""
+    HOST_DAS4_MYNODENUMBERS=""
 
     HOST_DAS4_COMMAND="`which ssh` -T -n -o BatchMode=yes"
     if [ ! -z "$HOST_DAS4_USER" ]; then
@@ -319,7 +327,7 @@ function hostLoadSettings() {
 # @output   The output of the command on the host.
 ##
 function hostSendCommand() {
-    $HOST_DAS4_COMMAND "module load prun; if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit -1; fi; SCRIPTFILE=\`mktemp --tmpdir=`hostGetPersistentTestDir`\`; OUTFILE=\`mktemp --tmpdir=`hostGetPersistentTestDir`\`; echo \"#!/bin/bash\" > \$SCRIPTFILE; echo \"if [ ! -f `hostGetTestDir`/host_das4_nodenumber ]; then exit 0; fi; if [ \"\\\`cat `hostGetTestDir`/host_das4_nodenumber\\\`\" != \"$HOST_DAS4_NODENUMBER\" ]; then exit 0; fi\" >> \$SCRIPTFILE; echo \"( `quote "$1"` ) > \$OUTFILE\">> \$SCRIPTFILE; chmod +x \$SCRIPTFILE; prun -1 -reserve $HOST_DAS4_RESERVATIONID \$SCRIPTFILE $HOST_DAS4_NNODES >> `hostGetPersistentTestDir`/das4_prun_debug; cat \$OUTFILE"
+    $HOST_DAS4_COMMAND "module load prun; if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit -1; fi; SCRIPTFILE=\`mktemp --tmpdir=`hostGetPersistentTestDir`\`; OUTFILE=\`mktemp --tmpdir=`hostGetPersistentTestDir`\`; echo \"#!/bin/bash\" > \$SCRIPTFILE; echo \"if [ ! -f `hostGetTestDir`/host_das4_nodenumber ]; then exit 0; fi; if [ \"\\\`cat `hostGetTestDir`/host_das4_nodenumber\\\`\" != \"$HOST_DAS4_NODENUMBER\" ]; then exit 0; fi\" >> \$SCRIPTFILE; echo \"( `quote "$1"` ) > \$OUTFILE\">> \$SCRIPTFILE; chmod +x \$SCRIPTFILE; prun -1 -reserve $HOST_DAS4_RESERVATIONID \$SCRIPTFILE $HOST_DAS4_NNODES_ALL >> `hostGetPersistentTestDir`/das4_prun_debug; cat \$OUTFILE"
     
     # Send the command to a file on the das4 headnode
     # Call prun with the appropriate parameters to run the script on only the node associated with this host
@@ -413,7 +421,7 @@ function hostPrepare() {
 
     # Make sure the host is cleaned up when interrupted
     addCleanupCommand "hostCleanup" $HOST_CLEANUPIDX
-    
+
     # Create the temporary persistent directory and make sure it can be used (take HOST_REMOTEFOLDER into account).
     if [ -z "$HOST_REMOTEFOLDER" ]; then
         HOST_TEMPFOLDER=`$HOST_DAS4_COMMAND "mktemp -d --tmpdir=\"\\\`pwd\\\`\""`
@@ -424,53 +432,106 @@ function hostPrepare() {
         echo "HOST_TEMPFOLDER=\"$HOST_TEMPFOLDER\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     fi
 
-    # Reserve the requested nodes and wait for them to become available.
-    HOST_DAS4_RESERVATIONID=`$HOST_DAS4_COMMAND "module load prun; preserve -1 -# $HOST_DAS4_NNODES $HOST_DAS4_RESERVETIME | grep \"Reservation number\" | sed -e \"s/^Reservation number \\([[:digit:]]*\\):$/\\1/\" | grep -E \"^[[:digit:]]*$\""`
-    if [ -z "$HOST_DAS4_RESERVATIONID" ]; then
-        logError "host:das4 :: Could not reserve the nodes. No reservation ID found."
-        fail
-    fi
-    echo "HOST_DAS4_RESERVATIONID=\"$HOST_DAS4_RESERVATIONID\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
-    ( echo "Waiting for DAS4 nodes to become available" >&2 ) > /dev/null
-    # FIXME FIXME There are some statusses that will result in bogus data!
-    # Example result of nodes:
-    # Nodes available, but unreachable: 8698  tschaap         11/08   13:59   11/08   14:01   t       2       -
-    local ans=`$HOST_DAS4_COMMAND "module load prun; while ! qstat -j $HOST_DAS4_RESERVATIONID | grep \"usage\" >/dev/null 2>/dev/null; do if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit 1; fi; sleep 1; done; while ! preserve -llist | grep -E \"^$HOST_DAS4_RESERVATIONID[[:space:]]\" | sed -e \"s/^[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*r[[:space:]][[:space:]]*[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*\\(.*\\)$/\\1/\" | grep -v -E \"^$HOST_DAS4_RESERVATIONID[[:space:]]\" > /dev/null; do if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit 1; fi; sleep 1; done; echo -n \"OK\""`
-    if [ "$ans" != "OK" ]; then
-        logError "host:das4 :: Nodes never became available and the reservation seems to be gone as well. Output follows."
-        logError $ans
-        ( echo "Nodes not available" >&2 ) > /dev/null
-        fail
-    fi
-    local nodes=`$HOST_DAS4_COMMAND "module load prun; preserve -llist | grep -E \"^$HOST_DAS4_RESERVATIONID[[:space:]]\" | sed -e \"s/^[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*r[[:space:]][[:space:]]*[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*\\(.*\\)$/\\1/\""`
-    if [ -z "$nodes" ]; then
-        logError "host:das4 :: Nodes could not be extracted from the reservation."
-        ( echo "Nodes available, but unknown" >&2 ) > /dev/null
-        fail
-    fi
-    if echo "$nodes" | grep -E "^$HOST_DAS4_RESERVATION_ID[[:space:]]" > /dev/null; then
-        logError "host:das4 :: Nodes could not be extracted from the reservation. Observed (and presumably incorrect) nodes: $nodes."
-        ( echo "Nodes available, but this seems to be wrong: $nodes" >&2 ) > /dev/null
-        fail
-    fi
-    local node=""
-    local checkcmd=""
-    for node in $nodes; do
-        checkcmd="$checkcmd ssh -n -T -o BatchMode=yes $node && "
-    done
-    ans=`$HOST_DAS4_COMMAND "module load prun; if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit -1; fi; $checkcmd echo -n \"OK\""`
-    if [ "$ans" != "OK" ]; then
-        logError "host:das4 :: Nodes found, but not all could be reached from the headnode. List of nodes and output follows."
-        logError "$nodes"
-        logError "$ans"
-        ( echo "Nodes available, but unreachable: $nodes" >&2 ) > /dev/null
-        fail
-    fi
-    ( echo "Nodes available: $nodes" >&2 ) > /dev/null
+    if [ "$HOST_DAS4_MASTER" = "1" ]; then
+        # Find out how much nodes are needed *in total* for all das4 hosts
+        local host=""
+        HOST_DAS4_NNODES_ALL=$HOST_DAS4_NNODES
+        local otherDAS4Hosts=( )
+        local otherDAS4HostNNodes=( )
+        for host in $HOSTS; do
+            if [ "$host" = "$HOST_NAME" ]; then
+                continue
+            fi
+            if [ -f "${LOCAL_TEST_DIR}/hosts/$host/modulename" ] && [ "`cat \"${LOCAL_TEST_DIR}/hosts/$host/modulename\"`" = "das4" ]; then
+                local moreNodes=`( hostLoadSettings $host; echo $HOST_DAS4_NNODES )`
+                HOST_DAS4_NNODES_ALL=$(($HOST_DAS4_NNODES_ALL + $moreNodes))
+                echo "HOST_DAS4_NNODES_ALL=\"$HOST_DAS4_NNODES_ALL\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+                otherDAS4Hosts[${#otherDAS4Hosts[@]}]=$host
+                otherDAS4HostNNodes[${#otherDAS4HostNNodes[@]}]=$moreNodes
+            fi
+        done
+
+        # Reserve the requested nodes and wait for them to become available.
+        HOST_DAS4_RESERVATIONID=`$HOST_DAS4_COMMAND "module load prun; preserve -1 -# $HOST_DAS4_NNODES_ALL $HOST_DAS4_RESERVETIME | grep \"Reservation number\" | sed -e \"s/^Reservation number \\([[:digit:]]*\\):$/\\1/\" | grep -E \"^[[:digit:]]*$\""`
+        if [ -z "$HOST_DAS4_RESERVATIONID" ]; then
+            logError "host:das4 :: Could not reserve the nodes. No reservation ID found."
+            fail
+        fi
+        echo "HOST_DAS4_RESERVATIONID=\"$HOST_DAS4_RESERVATIONID\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+        ( echo "Waiting for DAS4 nodes to become available" >&2 ) > /dev/null
+        # FIXME FIXME There are some statusses that will result in bogus data!
+        # Example result of nodes:
+        # Nodes available, but unreachable: 8698  tschaap         11/08   13:59   11/08   14:01   t       2       -
+        local ans=`$HOST_DAS4_COMMAND "module load prun; while ! qstat -j $HOST_DAS4_RESERVATIONID | grep \"usage\" >/dev/null 2>/dev/null; do if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit 1; fi; sleep 1; done; while ! preserve -llist | grep -E \"^$HOST_DAS4_RESERVATIONID[[:space:]]\" | sed -e \"s/^[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*r[[:space:]][[:space:]]*[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*\\(.*\\)$/\\1/\" | grep -v -E \"^$HOST_DAS4_RESERVATIONID[[:space:]]\" > /dev/null; do if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit 1; fi; sleep 1; done; echo -n \"OK\""`
+        if [ "$ans" != "OK" ]; then
+            logError "host:das4 :: Nodes never became available and the reservation seems to be gone as well. Output follows."
+            logError $ans
+            ( echo "Nodes not available" >&2 ) > /dev/null
+            fail
+        fi
+        local nodes=`$HOST_DAS4_COMMAND "module load prun; preserve -llist | grep -E \"^$HOST_DAS4_RESERVATIONID[[:space:]]\" | sed -e \"s/^[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*r[[:space:]][[:space:]]*[[:digit:]][[:digit:]]*[[:space:]][[:space:]]*\\(.*\\)$/\\1/\""`
+        if [ -z "$nodes" ]; then
+            logError "host:das4 :: Nodes could not be extracted from the reservation."
+            ( echo "Nodes available, but unknown" >&2 ) > /dev/null
+            fail
+        fi
+        if echo "$nodes" | grep -E "^$HOST_DAS4_RESERVATION_ID[[:space:]]" > /dev/null; then
+            logError "host:das4 :: Nodes could not be extracted from the reservation. Observed (and presumed incorrect) nodes: $nodes."
+            ( echo "Nodes available, but this seems to be wrong: $nodes" >&2 ) > /dev/null
+            fail
+        fi
+        local node=""
+        local checkcmd=""
+        for node in $nodes; do
+            checkcmd="$checkcmd ssh -n -T -o BatchMode=yes $node && "
+        done
+        ans=`$HOST_DAS4_COMMAND "module load prun; if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit -1; fi; $checkcmd echo -n \"OK\""`
+        if [ "$ans" != "OK" ]; then
+            logError "host:das4 :: Nodes found, but not all could be reached from the headnode. List of nodes and output follows."
+            logError "$nodes"
+            logError "$ans"
+            ( echo "Nodes available, but unreachable: $nodes" >&2 ) > /dev/null
+            fail
+        fi
+        ( echo "Nodes available: $nodes" >&2 ) > /dev/null
+
+        # Divide the nodes among the das4 non-slave hosts
+        local nodeSet=""
+        local nodeNumberSet=""
+        local nextNNodes=$HOST_DAS4_NNODES
+        local setCount=-1
+        local nodeCounter=0
+        otherDAS4HostNNodes[${#otherDAS4HostNNodes[@]}]=0
+        for node in $nodes; do
+            nodeSet="$nodeSet $node"
+            nodeNumberSet="$nodeNumberSet $nodeCounter"
+            nodeCounter=$(($nodeCounter + 1))
+            nextNNodes=$(($nextNNodes - 1))
+            if [ $nextNNodes -gt 0 ]; then
+                continue
+            fi
+            if [ $setCount -eq -1 ]; then
+                HOST_DAS4_MYNODES="$nodeSet"
+                HOST_DAS4_MYNODENUMBERS="$nodeNumberSet"
+                echo "HOST_DAS4_MYNODES=\"$HOST_DAS4_MYNODES\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+                echo "HOST_DAS4_MYNODENUMBERS=\"$HOST_DAS4_MYNODENUMBERS\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
+            else
+                echo "HOST_DAS4_RESERVATIONID=\"$HOST_DAS4_RESERVATIONID\"" >> "${LOCAL_TEST_DIR}/hosts/${otherDAS4Hosts[$setCount]}/conf"
+                echo "HOST_DAS4_MASTER=\"0\"" >> "${LOCAL_TEST_DIR}/hosts/${otherDAS4Hosts[$setCount]}/conf"
+                echo "HOST_DAS4_NNODES_ALL=\"$HOST_DAS4_NNODES_ALL\"" >> "${LOCAL_TEST_DIR}/hosts/${otherDAS4Hosts[$setCount]}/conf"
+                echo "HOST_DAS4_MYNODES=\"$nodeSet\"" >> "${LOCAL_TEST_DIR}/hosts/${otherDAS4Hosts[$setCount]}/conf"
+                echo "HOST_DAS4_MYNODENUMBERS=\"$nodeNumberSet\"" >> "${LOCAL_TEST_DIR}/hosts/${otherDAS4Hosts[$setCount]}/conf"
+            fi
+            setCount=$(($setCount + 1))
+            nextNNodes=${otherDAS4HostNNodes[$setCount]}
+            nodeSet=""
+            nodeNumberSet=""
+        done
+    fi  # if [ "$HOST_DAS4_MASTER" = "1" ]
 
     # Create SFTP forwarding scripts
     local cmd="mkdir -p `hostGetPersistentTestDir`/das4_sftp"
-    for node in $nodes; do
+    for node in $HOST_DAS4_MYNODES; do
         cmd="$cmd && echo \"ssh -o BatchMode=yes -s $node sftp\" > `hostGetPersistentTestDir`/das4_sftp/sftp_fwd_$node && chmod +x `hostGetPersistentTestDir`/das4_sftp/sftp_fwd_$node"
     done
     ans=`$HOST_DAS4_COMMAND "$cmd && echo -n \"OK\""`
@@ -486,9 +547,13 @@ function hostPrepare() {
     # Set this host to become the first node, the rest need to be spun off; shouldn't take too much effort, given that a new object is just a single file with settings (and a mention in HOSTS).
 
     # Set the master's node number (0), node name and create the temporary directory there, including number-tag
-    HOST_DAS4_NODENUMBER=0
-    for node in $nodes; do
+    for node in $HOST_DAS4_MYNODES; do
         HOST_DAS4_NODENAME="$node"
+        break
+    done
+    local number=0
+    for number in $HOST_DAS4_MYNODENUMBERS; do
+        HOST_DAS4_NODENUMBER="$number"
         break
     done
     echo "HOST_DAS4_NODENUMBER=\"$HOST_DAS4_NODENUMBER\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
@@ -517,22 +582,29 @@ function hostPrepare() {
         cp "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/modulename" "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/modulename"
         cp "$confcopy" "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
         echo "HOST_NAME=\"$HOST_NAME!$hostcount\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
+        echo "HOST_DAS4_MASTER=\"0\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
         echo "HOST_DAS4_SLAVE=\"1\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
-        echo "HOST_DAS4_NODENUMBER=\"$hostcount\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
         local i=0
         local thisnodename=""
-        for node in $nodes; do
+        local thisnodenumber=""
+        for node in $HOST_DAS4_MYNODES; do
             if [ $i -eq $hostcount ]; then
                 thisnodename="$node"
-                break;
+                break
+            fi
+            i=$(($i + 1))
+        done
+        i=0
+        for number in $HOST_DAS4_MYNODENUMBERS; do
+            if [ $i -eq $hostcount ]; then
+                thisnodenumber="$number"
+                break
             fi
             i=$(($i + 1))
         done
         echo "HOST_DAS4_NODENAME=\"$thisnodename\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
+        echo "HOST_DAS4_NODENUMBER=\"$thisnodenumber\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
         # Note that all the new host objects need to have their own cleanup file created and used.
-
-        # FIXME! FIXME! This addCleanupScript should actually try and insert the scripts into after the original cleanup script.
-        # This will require modding cleanup.sh
 
         addCleanupScript
         local idx=$?
@@ -542,7 +614,7 @@ function hostPrepare() {
         # The new hosts should have a temporary directory created on the node and it should be made sure they can be used.
         local thislocaltempdir=`$HOST_DAS4_COMMAND "module load prun; if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit -1; fi; ssh -n -T -o BatchMode=yes $thisnodename \"mkdir -p /local/$HOST_DAS4_USER; mktemp -d --tmpdir=/local/$HOST_DAS4_USER\""`
         echo "HOST_DAS4_LOCALTEMPDIRECTORY=\"$thislocaltempdir\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME!$hostcount/conf"
-        $HOST_DAS4_COMMAND "module load prun; if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit -1; fi; ssh -n -T -o BatchMode=yes $thisnodename \"echo -n $hostcount > $thislocaltempdir/host_das4_nodenumber\""
+        $HOST_DAS4_COMMAND "module load prun; if ! qstat -j $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; then exit -1; fi; ssh -n -T -o BatchMode=yes $thisnodename \"echo -n $thisnodenumber > $thislocaltempdir/host_das4_nodenumber\""
         HOSTS="$HOSTS $HOST_NAME!$hostcount"
         hostcount=$(($hostcount + 1))
     done
@@ -590,15 +662,18 @@ function hostCleanup() {
         echo "HOST_DAS4_LOCALTEMPDIRECTORY=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
     fi
 
-    # If this is the parent object, make sure to also cancel the reservation and remove the persistent temp dir.
+    # If this is the parent object, make sure to remove the persistent temp dir.
     if [ "$HOST_DAS4_SLAVE" != "1" ]; then
-        if [ -z "$HOST_TEMPFOLDER" ]; then
-            $HOST_DAS4_COMMAND "module load prun; preserve -c $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null"
-        else
-            $HOST_DAS4_COMMAND "module load prun; preserve -c $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null; rm -rf $HOST_TEMPFOLDER"
+        if [ ! -z "$HOST_TEMPFOLDER" ]; then
+            $HOST_DAS4_COMMAND "rm -rf $HOST_TEMPFOLDER"
             HOST_TEMPFOLDER=""
             echo "HOST_DAS4_TEMPFOLDER=\"\"" >> "${LOCAL_TEST_DIR}/hosts/$HOST_NAME/conf"
         fi
+    fi
+
+    # If this is the parent of all DAS4 hosts, make sure to also cancel the reservation
+    if [ "$HOST_DAS4_MASTER" = "1" ]; then
+        $HOST_DAS4_COMMAND "module load prun; preserve -c $HOST_DAS4_RESERVATIONID > /dev/null 2>/dev/null"
     fi
 
     removeCleanupScript $HOST_CLEANUPIDX
