Updated API version to 1.0.2. Please update all file modules!
Finalized, and added, client:utorrent, parser:utorrent and the accompanying ClientWrapper for utorrent.
Added createRemoteTempFile and createRemoteTempDir, and updated the documentation to basefunctions.sh.
Added metaFile parameter to generic files, and altered all file modules to handle it.
Extended file:local to work with local directories as well.
Updated README documentation for 1.0.2 API version.
Added file:fakedata and file:none, which allow for usage of generated fake data or no file at all.
Added Utils/fakedata/ which contains the utility used to generate fake data, both for the module and for manual usage.
Added a HOWTO to get you started.

diff --git a/ControlScripts/modules/parser/utorrent b/ControlScripts/modules/parser/utorrent
--- a/ControlScripts/modules/parser/utorrent
+++ b/ControlScripts/modules/parser/utorrent
@@ -1,17 +1,18 @@
 #!/bin/bash
 
 #
-# A test implementation for the parser API.
+# Implementation for the utorrent parser.
+# This module parses the utorrent logs to create a data file.
 #
 # Raw logs expected by this module:
-# - None (this is a test implementation that just outputs bogus data)
+# - log.log
 #
 # Parsed log files created by this module:
 # - log.data
-# -- logical time
-# -- file completion (%)
-# -- upload speed (kBps)
-# -- download speed (kBps)
+# -- relative time (seconds)
+# -- % done
+# -- upload speed (kB/s)
+# -- download speed (kB/s)
 #
 
 ##
@@ -44,7 +45,7 @@ function parserReadSettings() {
                 # These are the generic settings that have already been parsed. Usually one can ignore them as such.
                 ;;
             *)
-                logError "parser:test__ :: Unknown parameter name \"$parameterName\" in parser $PARSER_NAME. Ignoring."
+                logError "parser:_skeleton_ :: Unknown parameter name \"$parameterName\" in parser $PARSER_NAME. Ignoring."
                 ;;
         esac
         LINE_NUMBER=$(($LINE_NUMBER + 1))
@@ -66,7 +67,7 @@ function parserReadSettings() {
 ##
 function parserLoadSettings() {
     # By default delegated to the default implementation, which works fine if the default implementation for parserReadSettings is used
-    parserLoadSettings__default "$1" "test__"
+    parserLoadSettings__default "$1" "utorrent"
 }
 
 ##
@@ -75,7 +76,7 @@ function parserLoadSettings() {
 ##
 function parserLoadDefaultSettings() {
     PARSER_NAME=""
-    PARSER_SUBTYPE="test__"
+    PARSER_SUBTYPE="utorrent"
 }
 
 ##
@@ -88,26 +89,71 @@ function parserLoadDefaultSettings() {
 # @param    outputDir   The directory on the local machine where parsed logs are to be stored.
 ##
 function parserParseLogs() {
-    if [ ! -d $1 ]; then
-        logError "parser:test__::parserParseLogs(logDir,outputDir) was given logDir \"$1\", which seems not to exist."
+    if [ ! -f "$1/log.log" ]; then
+        logError "parser:utorrent :: Parser $PARSER_NAME expected log file \"$1/log.log\", but it's not there."
         fail
     fi
-    if [ ! -r $1 ]; then
-        logError "parser:test__::parserParseLogs(logDir,outputDir) was given logDir \"$1\", which seems not to be readable."
-        fail
-    fi
-    if [ ! -d $2 ]; then
-        logError "parser:test__::parserParseLogs(logDir,outputDir) was given outputDir \"$2\", which seems not to exist."
-        fail
-    fi
-    if [ ! -w $2 ]; then
-        logError "parser:test__::parserParseLogs(logDir,outputDir) was given outputDir \"$2\", which seems not t o be writable."
-        fail
-    fi
-    logError "parser:test just gives bogus output data. Have fun with them."
 
-    echo "0     50      10      20" > "$2/log.data"
-    echo "1     100     15      15" >> "$2/log.data"
+    if [ -f "$2/log.data" ]; then
+        logError "parser:utorrent :: Data file \"$2/log.data\" should be created by parser $PARSER_NAME, but it already exists."
+        fail
+    fi
+
+    touch "$2/log.data"
+
+    if [ ! -f "$2/log.data" ]; then
+        logError "parser:utorrent :: Could not touch output file $2/log.data."
+        return
+    fi
+
+    echo "time percent upspeed dlspeed" > "$2/log.data"
+    echo "0 0 0 0" >> "$2/log.data"
+
+    local firstTime=-1
+    local relTime=-1
+    local up_bytes=0
+    local down_bytes=0
+    local percentDone=""
+    while IFS="\n" read LINE; do
+        if [ "$firstTime" = "-1" ]; then
+            # This happens only the first time: an extra absolute timestamp is printed at the top
+            if ! echo "$LINE" | grep -E "^[[:digit:]]*\.[[:digit:]]*$" > /dev/null; then
+                continue
+            fi
+            firstTime=$LINE
+            continue
+        fi
+
+        if echo "$LINE" | grep -E "^[[:digit:]]*\.[[:digit:]]*$" > /dev/null; then
+            # Creates a relative timestamp
+            relTime=`echo "scale=6; ($LINE - $firstTime)" | bc`
+            continue
+        fi
+
+        if [ "$relTime" = "-1" ]; then
+            # Previous timestamp used, not using it again
+            continue
+        fi
+
+        # Granted, I'm not 100% sure that's a torrent line. There should be no other lines like this, though
+        if echo "$LINE" | grep -E "^\[\".*\",.*,.*,.*,.*,.*,.*,.*,.*" > /dev/null; then
+            # 5, 9, 10
+            # %, upspeed, downspeed
+
+            percentDone=`echo "$LINE" | sed -e "s/^[^,]*,[^,]*,[^,]*,[^,]*,\([^,]*\),.*$/\\1/"`
+            percentDone=`echo "scale=1; ($percentDone / 10.0)" | bc`
+
+            upspeed=`echo "$LINE" | sed -e "s/^[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,\([^,]*\),.*$/\1/"`
+            upspeed=`echo "scale=4; ($upspeed / 1024.0)" | bc`
+            downspeed=`echo "$LINE" | sed -e "s/^[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,\([^,]*\),.*$/\1/"`
+            downspeed=`echo "scale=4; ($downspeed / 1024.0)" | bc`
+
+            echo "$relTime $percentDone $upspeed $downspeed" >> "$2/log.data"
+
+            # Consume timestamp
+            relTime=-1
+        fi
+    done < "$1/log.log"
 }
 
 ##
