- Quite some fixes in the runner scripts for uTorrent. Works pretty well   now. - Added port parameter to client:http. - client:http now allows multiple connections per host (up to 16) - client:utorrent now logs errors and retrieves that log - host:das4 allows overriding the check for a correct headNode using the   new headNodeOverride parameter - host:das4 functions correctly with multiple executions - solved small problem with parser:aria2 for downloads longer than 1   minute - parser:aria2 now tries to use its new PHP implementation - parser:lighttpd now tries to use its new PHP implementation - parser:swift now tries to use its new PHP implementation - parser:utorrent now tries to use its new PHP implementation - slightly improved performance of run_scenarion using parallel   processes - added new callNonBash function to easily try and call a non-bash   implementation of a function

diff --git a/ControlScripts/modules/client/http b/ControlScripts/modules/client/http
--- a/ControlScripts/modules/client/http
+++ b/ControlScripts/modules/client/http
@@ -8,6 +8,7 @@
 #
 # Extra parameters recognized by client:lighttpd:
 # - useSSL : Set to anything but "no" to enable HTTPS instead of HTTP; may be specified multiple times, last declaration counts
+# - port : Use the specified port for server instances (positive integer < 65536; default 3000)
 #
 # When using SSL it is important to note that lighttpd then needs to be compiled with --with-openssl (not default). Also, the openssl utility must be available on the target seeding machines, or the server will fail to start.
 #
@@ -27,6 +28,7 @@ function clientReadSettings() {
     local parameterValue=""
     LINE_NUMBER=$(($2 + 1))
     CLIENT_HTTP_HTTPS=""
+    CLIENT_HTTP_PORT=""
     # Parse all parameters
     while IFS="" read LINE; do
         if [ "" = "$LINE" ]; then
@@ -49,6 +51,21 @@ function clientReadSettings() {
                     CLIENT_HTTP_HTTPS=""
                 fi
                 ;;
+            port)
+                if ! echo "$parameterValue" | grep -E "^[0-9][0-9]*$" > /dev/null; then
+                    logError "client:http :: $parameterName is not a port number in client $CLIENT_NAME on line $LINE_NUMBER."
+                    return 1
+                fi
+                if [ "$parameterValue" -gt 65535 ]; then
+                    logError "client:http :: port number $parameterName too high in client $CLIENT_NAME on line $LINE_NUMBER."
+                    return 1
+                fi
+                if [ ! -z "$CLIENT_HTTP_PORT" ]; then
+                    logError "client:http :: a port number has already been specified for client $CLIENT_NAME ($CLIENT_HTTP_PORT), found a new port number ($parameterName) on line $LINE_NUMBER."
+                    return 1
+                fi
+                CLIENT_HTTP_PORT=$parameterValue
+                ;;
             *)
                 logError "client:http :: Unknown parameter name \"$parameterName\" in client $CLIENT_NAME on line $LINE_NUMBER. Ignoring."
                 ;;
@@ -56,11 +73,16 @@ function clientReadSettings() {
         LINE_NUMBER=$(($LINE_NUMBER + 1))
     done < "$1";
 
+    if [ -z "$CLIENT_HTTP_PORT" ]; then
+        CLIENT_HTTP_PORT=3000
+    fi
+
     # Delegate the rest to the default implementation
     clientReadSettings__default
     # Any variables set up above should be saved like this:
     # echo "YOUR_SETTING=\"$YOUR_SETTING\"" >> "${LOCAL_TEST_DIR}/clients/$CLIENT_NAME/conf"
     echo "CLIENT_HTTP_HTTPS=\"$CLIENT_HTTP_HTTPS\"" >> "${LOCAL_TEST_DIR}/clients/$CLIENT_NAME/conf"
+    echo "CLIENT_HTTP_PORT=\"$CLIENT_HTTP_PORT\"" >> "${LOCAL_TEST_DIR}/clients/$CLIENT_NAME/conf"
 
     # Finally, register our client with the environment
     CLIENTS="$CLIENTS $CLIENT_NAME"
@@ -230,6 +252,7 @@ function clientPrepareExecution() {
                 continue
             fi
             executionLoadHost
+            executionLoadClient
             seederhost=`hostGetAddress`
             if [ -z "$seederhost" ]; then
                 logError "client:http :: HTTP leeching client $CLIENT_NAME requires all seeders to give their address, but hostGetAddress for host $HOST_NAME returns \"\""
@@ -237,14 +260,15 @@ function clientPrepareExecution() {
             fi
 
             if [ -z "$CLIENT_HTTP_HTTPS" ]; then
-                seeders="$seeders \"http://$seederhost:3000/$filename\""
+                seeders="$seeders \"http://$seederhost:$CLIENT_HTTP_PORT/$filename\""
             else
-                seeders="$seeders \"https://$seederhost:3000/$filename\""
+                seeders="$seeders \"https://$seederhost:$CLIENT_HTTP_PORT/$filename\""
             fi
             nseeders=$(($nseeders + 1))
         done
         executionLoadSettings $myExecNum
         executionLoadHost
+        executionLoadClient
         if [ $nseeders = 0 ]; then
             logError "client:http :: HTTP leeching client $CLIENT_NAME does not support leeching 0 seeders"
             fail
@@ -252,6 +276,8 @@ function clientPrepareExecution() {
         # Leecher client: run aria2
         # -j #seeders                           # maximum concurrent downloads
         # -s #seeders                           # split file in n parts
+        # -x #seeders                           # allow at most #seeders connection to each host (necessary for multiple servers on the same host, max 16!)
+        # --uri-selector=inorder                # forces aria to choose the next URI whenver trying to download another piece
         # --human-readable=false                # full output
         # --summary-interval=1                  # give output every 1 sec
         # --no-conf=true                        # don't read global conf
@@ -261,18 +287,19 @@ function clientPrepareExecution() {
         # --retry-wait=1                        # wait 1 sec between retries
         # --dir=`hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber`/   # save here
         # --check-certificate=false             # don't check our on-the-fly-generated self-signed certificates [SSL]
-        if [ -z "$CLIENT_HTTP_HTTPS" ]; then
-            clientPrepareExecution__default "./aria2c -j $nseeders -s $nseeders --human-readable=false --summary-interval=1 --no-conf=true --truncate-console-readout=false -n --max-tries=0 --retry-wait=1 --dir=`hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber`/ $seeders > `hostGetPersistentTestDir`/logs/$CLIENT_NAME/exec_`executionNumber`/log.log"
-        else
-            # The sleep 10 is a hack to work around slower setup of lighttpd which would cause aria2 to fail when connection to the server
-            clientPrepareExecution__default "sleep 10; ./aria2c -j $nseeders -s $nseeders --human-readable=false --summary-interval=1 --no-conf=true --truncate-console-readout=false -n --max-tries=0 --retry-wait=1 --dir=`hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber`/ --check-certificate=false $seeders > `hostGetPersistentTestDir`/logs/$CLIENT_NAME/exec_`executionNumber`/log.log"
+        # (SSL options are given anyway, since they don't matter for non-SSL)
+        # The sleep 30 is a hack to work around slower setup of lighttpd which would cause aria2 to fail when connecting to the server
+        local connperhost=$(($nseeders * 2))
+        if [ $connperhost -gt 16 ]; then
+            connperhost=16
         fi
+        clientPrepareExecution__default "sleep 30; ./aria2c -j $nseeders -s $nseeders -x $connperhost --uri-selector=inorder --human-readable=false --summary-interval=1 --no-conf=true --truncate-console-readout=false -n --max-tries=0 --retry-wait=1 --dir=`hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber`/ --check-certificate=false $seeders > `hostGetPersistentTestDir`/logs/$CLIENT_NAME/exec_`executionNumber`/log.log"
     else
         # Seeder client: run lighttpd
         if [ -z "$CLIENT_HTTP_HTTPS" ]; then
-            clientPrepareExecution__default "`hostGetTestDir`/clients/$CLIENT_NAME/lighttpd_logging `hostGetTestDir`/clients/$CLIENT_NAME `hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber` `fileGetName` > `hostGetPersistentTestDir`/logs/$CLIENT_NAME/exec_`executionNumber`/log.log"
+            clientPrepareExecution__default "`hostGetTestDir`/clients/$CLIENT_NAME/lighttpd_logging `hostGetTestDir`/clients/$CLIENT_NAME `hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber` `fileGetName` $CLIENT_HTTP_PORT > `hostGetPersistentTestDir`/logs/$CLIENT_NAME/exec_`executionNumber`/log.log"
         else
-            clientPrepareExecution__default "`hostGetTestDir`/clients/$CLIENT_NAME/lighttpd_logging `hostGetTestDir`/clients/$CLIENT_NAME `hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber` `fileGetName` SSL > `hostGetPersistentTestDir`/logs/$CLIENT_NAME/exec_`executionNumber`/log.log"
+            clientPrepareExecution__default "`hostGetTestDir`/clients/$CLIENT_NAME/lighttpd_logging `hostGetTestDir`/clients/$CLIENT_NAME `hostGetTestDir`/clients/$CLIENT_NAME/exec_`executionNumber` `fileGetName` $CLIENT_HTTP_PORT SSL > `hostGetPersistentTestDir`/logs/$CLIENT_NAME/exec_`executionNumber`/log.log"
         fi
     fi
 
@@ -382,7 +409,7 @@ function clientTrafficInboundPorts() {
 # @output   The list of outbound ports that would capture all outgoing traffic.
 ##
 function clientTrafficOutboundPorts() {
-    echo "3000"
+    echo $CLIENT_HTTP_PORT
 }
 
 ##
